trigger:
- '*'
pr:
- '*'

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: 'macOS-10.15'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- bash: |
    /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    echo ">>> Started xvfb"
  displayName: Start xvfb
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))

- bash: |
    echo ">>> Compile starcoin-ide"
    yarn && yarn compile
    echo ">>> Compiled starcoin-ide"
    echo ">>> Run unit test and integration test"
    yarn && yarn test
  displayName: Run Tests
  env:
    DISPLAY: ':99.0'
